// gen-tokens.js - the brand token emitter (upgrade P5, 2026-07-12, design 1.6/4.5).
//
// Emits the two COMMITTED brand-token artifacts from the ALREADY-PARSED color law
// (read-sources parseColorTokens -> model.colorTokens). This module NEVER re-parses
// brand/config/color-system.md itself - the read-sources contract is the single way the
// law file is read, so the generator and the validator can never disagree about it.
//
//   work/16-alex-hq/app/app/tokens.css   :root { --color-{kebab-name}: #hex; ... }
//   brand/tokens/tokens.json             { _generated, _source, tokens: { name -> hex } }
//
// Both artifacts are committed (the Hetzner box builds the HQ app in Docker WITHOUT the
// generator, so the token layer must exist in the tree). Drift protection: validate-alex V8
// regenerates via these exact functions and fails the run if the on-disk copy differs.
'use strict';

const CSS_REL = 'work/16-alex-hq/app/app/tokens.css';
const JSON_REL = 'brand/tokens/tokens.json';
const HEADER = 'GENERATED by scripts/generate-alex.js from brand/config/color-system.md - never hand-edit';

const kebab = name => name.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

// colorTokens = { tokens: Map(name -> #hex), allHexes: Set } (parseColorTokens contract).
function tokensCss(colorTokens) {
  const lines = [
    `/* ${HEADER}.`,
    '   One custom property per named token in the color law (core palette + extended palette).',
    '   Consumers alias these (globals.css); V8 fails the generator when this file is stale. */',
    ':root {',
  ];
  for (const [name, hex] of colorTokens.tokens) lines.push(`  --color-${kebab(name)}: ${hex};`);
  lines.push('}', '');
  return lines.join('\n');
}

function tokensJson(colorTokens) {
  const out = {
    _generated: HEADER,
    _source: 'brand/config/color-system.md',
    tokens: {},
  };
  for (const [name, hex] of colorTokens.tokens) out.tokens[name] = hex;
  return JSON.stringify(out, null, 2) + '\n';
}

module.exports = { CSS_REL, JSON_REL, HEADER, kebab, tokensCss, tokensJson };
