/// All jobs that hit the Stage 3 gate, with pass/needs_review outcome. Source: Job Search Pipeline sheet.
table processed_jobs
	lineageTag: 50115a6f-1509-4cde-a4a2-fc9d99190e6e

	measure 'Jobs Processed' = COUNTROWS(processed_jobs)
		formatString: #,0
		lineageTag: e86032dd-184f-4088-aba2-197bd1ebaf16

	/// Jobs the gate routed to manual review. The pile waiting for Shaheen.
	measure 'Apps To Review' = CALCULATE(COUNTROWS(processed_jobs), processed_jobs[gate_status] = "needs_review")
		formatString: #,0
		lineageTag: 59a71e68-87ef-47e7-a850-dfa882b8cef1

	/// Drafted applications (CV + cover letter in Drive) waiting for submit.
	measure 'Apps Ready To Apply' = CALCULATE(COUNTROWS(run_log), run_log[status] = "draft_ready")
		formatString: #,0
		lineageTag: 8af9f7c2-e4c6-4283-aed5-77ed83d28dad

	measure 'Pass Rate' = DIVIDE(CALCULATE(COUNTROWS(processed_jobs), processed_jobs[gate_status] = "pass"), COUNTROWS(processed_jobs))
		formatString: 0.0%
		lineageTag: 77698450-d45d-46a6-b15f-98c09ff0881b

	column job_posting_id
		dataType: int64
		lineageTag: 2011da1b-1ef2-40c2-b511-14cbcebd171b
		summarizeBy: sum
		sourceColumn: job_posting_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c5bdcbff-a9fa-4e4c-8e71-a6b4ebb86cea
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 23544d04-2c20-4839-8c48-1f7bd4218d15
			defaultHierarchy: LocalDateTable_2e7cbb3e-bbf8-4dbd-bff2-24f8900d0546.'Date Hierarchy'

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column company_name
		dataType: string
		lineageTag: f55f41c9-6123-4e3b-a5c2-2beeff7d6282
		summarizeBy: none
		sourceColumn: company_name

		annotation SummarizationSetBy = Automatic

	column job_title
		dataType: string
		lineageTag: f4605af8-f5b1-4b86-85e1-63394849b256
		summarizeBy: none
		sourceColumn: job_title

		annotation SummarizationSetBy = Automatic

	column gate_status
		dataType: string
		lineageTag: f8ccf586-eb42-4dfa-bec0-e9a5488c0f23
		summarizeBy: none
		sourceColumn: gate_status

		annotation SummarizationSetBy = Automatic

	partition processed_jobs = m
		mode: import
		source = let Source = Excel.Workbook(File.Contents("C:\Users\Thinkpad\Desktop\personal-os\work\03-application-engine\powerbi\job-search-pipeline.xlsx"), null, true), Sheet = Source{[Item="processed_jobs",Kind="Sheet"]}[Data], Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]), Selected = Table.SelectColumns(Promoted, {"job_posting_id", "date", "company_name", "job_title", "gate_status"}), Typed = Table.TransformColumnTypes(Selected, {{"job_posting_id", Int64.Type}, {"date", type date}, {"company_name", type text}, {"job_title", type text}, {"gate_status", type text}}) in Typed

